- id: set_joe_home_state
  alias: Set Joe Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: home
- id: set_joe_not_home_state
  alias: Set Joe Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: not_home
- id: set_jamie_home_state
  alias: Set Jamie Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: home
- id: set_jamie_not_home_state
  alias: Set Jamie Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: not_home
- id: '1657994392567'
  alias: TV On
  description: ''
  trigger: []
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.tv
      - switch.home_theater
  mode: single
- id: '1657994761588'
  alias: TV Off
  description: ''
  trigger: []
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.tv
      - switch.home_theater
  mode: single
- id: set_trusted_home
  alias: Set Trusted Home
  description: ''
  trigger:
  - platform: state
    entity_id: person.joe_thomas
  - platform: state
    entity_id: person.jamie_thomas
  - platform: time
    at: 07:00:00
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ states(''person.joe_thomas'').lower()  == ''home'' or states(''person.jamie_thomas'').lower()
        == ''home'' }}'
    - condition: time
      after: 07:00:00
      before: 09:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: var.set
    data:
      entity_id:
      - var.trusted_home
      value: true
  mode: single
- id: set_not_trusted_home
  alias: Set Not Trusted Home
  description: ''
  trigger:
  - platform: state
    entity_id: person.joe_thomas
  - platform: state
    entity_id: person.jamie_thomas
  - platform: time
    at: 09:00:00
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states(''person.joe_thomas'').lower()  == ''home'' or
          states(''person.jamie_thomas'').lower() == ''home'' }}'
      - condition: time
        after: 07:00:00
        before: 09:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: var.set
    data:
      entity_id:
      - var.trusted_home
      value: false
- id: '1705886769813'
  alias: Restart Modem if no 34DT ping
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition:
  - condition: state
    entity_id: sensor.34dt_hassio
    state: Down
    for:
      hours: 0
      minutes: 1
      seconds: 0
  action:
  - service: notify.pushover
    data:
      message: Can't reach 34DT at midnight; rebooting modem
      title: Restart Modem
      target: six50joePhone
  - type: turn_off
    device_id: f15d84e8ec291475d43938976ffbd26f
    entity_id: switch.modem_smart_switch
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_on
    device_id: f15d84e8ec291475d43938976ffbd26f
    entity_id: switch.modem_smart_switch
    domain: switch
  mode: single
- id: '1706831665123'
  alias: Daily Enablement of Notifications
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: automation.trigger
    target:
      entity_id: automation.resume_notifications
    data:
      skip_condition: true
  mode: single
- id: '1768053204221'
  alias: Propane Level Low Alert
  description: Notify when heating propane drops below 30%.
  triggers:
  - entity_id: sensor.heating_propane_level
    below: 30
    trigger: numeric_state
  conditions:
  - condition: numeric_state
    entity_id: sensor.heating_propane_level
    above: 0.1
  actions:
  - data:
      message: 'Lake house Heating propane level is below 30%. Current level: {{ states(''sensor.heating_propane_level'')
        }}%'
      title: Lake housek Low Heating Propane Warning
    action: notify.pushover
  mode: single
