# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#lovelace:
#
# Add-On for lovelace
#
#  resources:
#    - url: /local/config-template-card/config-template-card.js
#      type: module

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named ha_homes_common/config

#
# Logging Levels
#
logger:
  default: info
  logs:
    # log level for HA core
    homeassistant.core: info

#
# Other home
#
command_line:
  - sensor:
      name: 34DT Hassio
      command: /usr/bin/nc -z -w7 deerjoe.groks-the.info 8123 && echo Up || echo Down

# All HA Variables
var: !include_dir_merge_named 12ridge_local/variables/

# Input booleans (person / home states)
# input_boolean: (in input_booleans.yaml)

# Automations I create in the UI
automation: !include automations.yaml

# 12R handmade automations
automation manual: !include_dir_merge_list 12ridge_local/automations/

# Sensors- Monitoring entities
sensor: !include_dir_merge_list 12ridge_local/sensors

# Where we all are
# Traccar yaml cfg deprecated
composite: !include 12ridge_local/device_trackers.yaml

# Binary sensors
binary_sensor: !include 12ridge_local/binary_sensor.yaml

# TV Switch and other manually created ones
switch: !include 12ridge_local/switches.yaml

# House lighting 
light: !include 12ridge_local/lights.yaml

# Scenes
scene: !include scenes.yaml

#
# Device Tracking
#
device_tracker:
   - platform: traccar
     host: deerjoe.groks-the.info
     port: 8082
     username: six50joe@gmail.com
     password: tuneless-bone-mash
     monitored_conditions: ['all_events']
     ssl: false
     verify_ssl: false
     new_device_defaults:
       track_new_devices: true

# House cameras
amcrest: !include 12ridge_local/cameras.yaml

shopping_list:

input_number: !include 12ridge_local/input_number.yaml


influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
  default_measurement: state